### ISSUE TITLE
Which variant is right?

### ISSUE THREAD

**Issue by elky** [sproutcore/TransformJS#1]
Hi guys,

Which variant of the final image state is right?

**Chrome 13:** http://dl.dropbox.com/u/2573685/tranformjs-chrome.jpg
**Firefox 6:** http://dl.dropbox.com/u/2573685/tranformjs-ff.jpg

Thanks.

**Comment by jtaby** [comment]
Since Firefox does not support 3D transforms, Firefox will just apply the 2D ones and ignore the 3D ones, so both are correct :)

**Comment by elky** [comment]
Yeah, but I mean that Firefox flips image vertically. So is it possible to rotate the image more for a normal state (specially for non-webkit browsers)?

**Comment by jtaby** [comment]
The reason it's flipped upside down in Chrome is because rotateX is flipping it upside down, not because rotateY is running twice. I tried doubling the rotateY animation but it doesn't look as good O_o

I was thinking of changing the demo and turning it into a table where each row represents a single animation. Thoughts?

**Comment by elky** [comment]
Try this in FF in your demo:

<pre>rotateZ: '+='+(2*Math.PI)</pre>

It looks good now. But in Chrome it's flipped, lol. 
So I think you need to add special rules for browsers which doesn't support 3D transforms.

**Comment by jtaby** [comment]
I recorded a screencast using Firefox 6.0 and Chrome 15 and the results look identical for me. Here's the video: http://cl.ly/3e3I2O2H2j3b1x1B2I0k

**Comment by elky** [comment]
That's strange...

**Comment by jtaby** [comment]
Closing issue pending further information...
